### ISSUE TITLE
Persiapan Administratif MTCNA Batch #9

### ISSUE THREAD

**Issue by sidiqfer** [STT-Terpadu-Nurul-Fikri/NETS#2]
- [x] Surat Izin Peminjaman Ruangan kepada KEMAHASISWAAN dan BSP
- [x] Pembuatan Surat Izin dari NETS ke BAAK untuk mahasiswa kelas Weekend
- [x] Penyerahan Surat Izin kepada BAAK
- [x] Pemberian info kepada mahasiswa bahwa surat izin sudah diacc
- [x] Pencetakan SERTIFIKAT KELULUSAN

**Comment by sidiqfer** [comment]
@sidiqfer - [x] Surat Izin Peminjaman Ruangan kepada KEMAHASISWAAN dan BSP (DONE)

**Comment by slamets75** [comment]
MTCNA Batch 9 Alhamdulillah sudah selesai dilakukan dan berjalan lancar.


![MTCNA Batch 9 - 25122020](https://user-images.githubusercontent.com/22762466/103198214-57720680-491a-11eb-82aa-02e5e44649c7.jpg)
