### ISSUE TITLE
Integrasi Github dengan GitHubBot di Telegram.

### ISSUE THREAD

**Issue by slamets75** [STT-Terpadu-Nurul-Fikri/NETS#4]
Mas @Yusmann mencoba dengan apik integrasi repo STTNF/NETS ke dalam group pengurus NETS.

**Comment by Yusmann** [comment]
@slamets75 Berarti yang saya ketik ini, otomatis muncul di komen github juga ya pakk? Kalo update utk progress yg ada di issue bisa dari reply komen gini juga ngga ya ?

**Comment by slamets75** [comment]
@Yusmann Bisa, akan tampil jika akun mas @Yusmann sudah konek ke githubBot

**Comment by Yusmann** [comment]
@slamets75 Pengetikannya spt apa pak ? Kalo di githubnya kan itu tinggal di klik checkboxnya. Terus, adakah command utk show list issuesnya disini?

**Comment by slamets75** [comment]
Integrasi github sudah selesai ya, tiket saya tutup (closed)
