### ISSUE TITLE
Progress Mengajar MTCNA Batch 9

### ISSUE THREAD

**Issue by Yusmann** [STT-Terpadu-Nurul-Fikri/NETS#5]
Pertemuan terakhir sampai dengan MODUL 5 Wireless LAB 5.1.

**Comment by Yusmann** [comment]
Attachement Slide MTCNA NETS: 
https://docs.google.com/presentation/d/1KfByzckDn26MhzeEUQzFkXEgzeObwJf-P9c7m6QwcTM/edit#slide=id.gc6f919934_0_0

**Comment by slamets75** [comment]
Semua modul 1-9 sudah selesai disampaikan.

Ahamdulillah teman-teman MTCNA batch 9 diantaranya:
- David Octavyanto
- Muhammad Ridho Hafidz
- Rio Agi
- Muhammad Rifqi
- Eko Depa Nugraha
- Raihan Kaeni Smit
- Muhammad Aji Bayu Purbaning Katon


Lulus ujian sertifikasi MTCNA batch 9.


![MTCNA Batch 9 - 25122020](https://user-images.githubusercontent.com/22762466/103198382-c7808c80-491a-11eb-8ba0-e2d3d8c195ba.jpg)
